spring:
  application:
    name: zuul-server  # Service registers under this name
  # Added to fix -  java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut hystrixCommandAnnotationPointcut
  #aop:
  #  auto: false
  # There was an issue with RC build of Streams, therefore used the build.snapshot.
  # Once stable version is released allow-bean-definition-overriding can be removed.
#  main:
#    allow-bean-definition-overriding: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    restaurantapi:
      path: /restaurantapi/**
      serviceId: restaurant-service
      stripPrefix: true
    bookingapi:
      path: /bookingapi/**
      serviceId: booking-service
      stripPrefix: true
    userapi:
      path: /userapi/**
      serviceId: user-service
      stripPrefix: true

server:
  port: 8765
  compression:
    enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId:  ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

  client:
    instance:
      registryFetchIntervalSeconds: 5
      instanceInfoReplicationInvervalSeconds: 5
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
        defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/
      fetchRegistry: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

app:
  ConnectTimeout: 100
  ReadTimeout: 3000

---
spring:
  aop:
    auto: false
  profiles: docker

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://restaurant-eureka:8761/eureka/
      fetchRegistry: true
      healthcheck:
        enabled: true
